### ISSUE TITLE
导航栏jekyll设置无效

### ISSUE THREAD

**Issue by liuyun16** [huajianmao/huajianmao.github.io#11]
你好！
看见你的博客文章，[Github Pages博客搭建过程记录 @ 技术杂货铺hjmao](https://huajianmao.github.io/how-i-setup-this-blog/)。觉得写得很好，但是，按照你的操作，能新建出导航标签来，但是jekell不能在该标签下实现目录中.md文件的生成，请问是怎么回事？
例如，
我理解的新建“笔记”栏，
1. 在/_data/navigation.yml中，加入：
```
  - title: "笔记"
    url: /notes/
```
2. 新建/_note文件夹，写入YY-MM-DD-title.md。

3. 在/_pages/增加，`notes.html`页面，写入内容：
```
---
layout: archive
permalink: /notes/
title: "Notes"
author_profile: true
---

{% for post in site.notes reversed %}
  {% include archive-single.html %}
{% endfor %}
```

4. 在/_config.yml文件中，增加：
```
collections:
   notes:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _notes
  - scope:
      path: ""
      type: notes
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

```

但，我做完了之后，依然看不到，我在_note/下面写入的.md博客？？
请问有什么可能导致错误？
